# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wh0XJIynJlHrXJ8yRzoELyph5mPIx_d1
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

data = {
    "A" : [1,2,3,4,5,6,7],
    "B" : [10,20,30,40,50,60,70]
}

df = pd.DataFrame(data)
df.head()

plt.figure(figsize = (10,6))
plt.bar(df.index, df["B"], color = 'orange')
plt.title("Bar Graph")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.show()

data1 = {
    "nilu" : [1000,2000,3000,4000,5000,6000,7000],
    "prapti" : [1550,5520,5430,4560,5870,6340,9870]
}

df1 = pd.DataFrame(data1)
df1.head()

#line plot
plt.figure(figsize = (10,6))
plt.plot(df1.index, df1["nilu"], label = 'nilu',marker ='o')
plt.plot(df1.index, df1["prapti"],label = 'prapti',marker ='x')
plt.title("Line Plot")
plt.xlabel("Index")
plt.ylabel("Value")
plt.legend()
plt.grid(True)

plt.show()

labels = ['Dancing', 'Singing', 'Studying', 'Reading', 'Learning', 'Writing']
values = [10, 20, 30, 40, 50, 60]

plt.pie(values, labels = labels,radius=1, autopct = '%1.1f%%')
plt.title("Qualities in Me")
plt.show()